// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiVPEWAN8wxhkZQMZXoruJamcMiQISG6I',
    appId: '1:98173172500:web:058fe1b15c89ec78f22001',
    messagingSenderId: '98173172500',
    projectId: 'ptielections-2024',
    authDomain: 'ptielections-2024.firebaseapp.com',
    storageBucket: 'ptielections-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkcMmNe4eRDTo5MP6zRyxJif-Q37U_Fk',
    appId: '1:98173172500:android:f25c1c2428ee18c0f22001',
    messagingSenderId: '98173172500',
    projectId: 'ptielections-2024',
    storageBucket: 'ptielections-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtwJIziCPLn42Z6cGTfDrPZ54TvFu3E2k',
    appId: '1:98173172500:ios:6f70da00942184d4f22001',
    messagingSenderId: '98173172500',
    projectId: 'ptielections-2024',
    storageBucket: 'ptielections-2024.appspot.com',
    iosBundleId: 'com.fahadwaseem.ptielections.ptiElections',
  );
}
